#!/bin/bash

# automating the creation of new users

# setting name of csv file
CSV_FILE=names.csv

GROUP_NAME=developers

# check if the group exists
if [ $(getent group devlopers) ];
then
    echo group already exists
else
    sudo groupadd $GROUP_NAME
    echo group created successfully
fi